num = int(input('Digite um número para mostrar sua tabuada: '))
print('-------------------')
print(f'6 x {num} = {num *1 }')
print(f'6 x {num} = {num *2 }')
print(f'6 x {num} = {num *3 }')
print(f'6 x {num} = {num *4 }')
print(f'6 x {num} = {num *5 }')
print(f'6 x {num} = {num *6 }')
print(f'6 x {num} = {num *7 }')
print(f'6 x {num} = {num *8 }')
print(f'6 x {num} = {num *9 }')
print(f'6 x {num} = {num *10 }')
print('--------------------')